env:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_DATASOURCE_URL: "vault:eafdmmart/data/prod/fdm#url"
  SPRING_DATASOURCE_USERNAME: "vault:eafdmmart/data/prod/fdm#username"
  SPRING_DATASOURCE_PASSWORD: "vault:eafdmmart/data/prod/fdm#password"
  INTEGRATION_CAPABILITY_SERVER_URL: "vault:eafdmmart/data/prod/fdm#capabilityserver"
  INTEGRATION_TECHRADAR_SERVER_URL: "vault:eafdmmart/data/prod/fdm#techradarserverurl"

  JWKS: "vault:eafdmmart/data/prod/fdm#jwks"


replicaCount: 1