env:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_DATASOURCE_URL: "vault:eafdmmart/data/prod/fdm#url"
  SPRING_DATASOURCE_USERNAME: "vault:eafdmmart/data/prod/fdm#username"
  SPRING_DATASOURCE_PASSWORD: "vault:eafdmmart/data/prod/fdm#password"
  SPRING_RABBITMQ_TEMPLATE_ROUTING_KEY: "vault:eafdmmart/data/prod/fdm#rabbitmqtemplateroutingkey"
  SPRING_RABBITMQ_HOST: "vault:eafdmmart/data/prod/fdm#rabbitmqhost"
  SPRING_RABBITMQ_PORT: "vault:eafdmmart/data/prod/fdm#rabbitmqport"
  SPRING_RABBITMQ_USERNAME: "vault:eafdmmart/data/prod/fdm#rabbitmqusername"
  SPRING_RABBITMQ_PASSWORD: "vault:eafdmmart/data/prod/fdm#rabbitmqpassword"
  SPRING_RABBITMQ_VIRTUAL_HOST: "vault:eafdmmart/data/prod/fdm#rabbitmqvirtualhost"
  INTEGRATION_CAPABILITY_SERVER_URL: "vault:eafdmmart/data/prod/fdm#capabilityserver"
  INTEGRATION_TECHRADAR_SERVER_URL: "vault:eafdmmart/data/prod/fdm#techradarserverurl"
  INTEGRATION_AUTHSSO_SERVER_URL: "vault:eafdmmart/data/prod/ambassador#authsso"
  INTEGRATION_GRAPH_SERVER_URL: "vault:eafdmmart/data/prod/fdm#graphserverurl"
  INTEGRATION_AUTH_SERVER_URL: "vault:eafdmmart/data/prod/fdm#authserverurl"
  OTEL_EXPORTER_OTLP_ENDPOINT: "vault:eafdmmart/data/prod/fdm#opentelemetry"
  JWKS: "vault:eafdmmart/data/prod/fdm#jwks"

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: Content-Type, authorization
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, DELETE, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

replicaCount: 1