env:
  JAVACMD: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8090"
  SPRING_PROFILES_ACTIVE: func
  SPRING_DATASOURCE_URL: "vault:eafdmmart/data/test/func/fdm#url"
  SPRING_DATASOURCE_USERNAME: "vault:eafdmmart/data/test/func/fdm#username"
  SPRING_DATASOURCE_PASSWORD: "vault:eafdmmart/data/test/func/fdm#password"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "vault:eafdmmart/data/test/func/fdm#driver"
  SPRING_RABBITMQ_TEMPLATE_ROUTING_KEY: "vault:eafdmmart/data/test/func/fdm#rabbitmqtemplateroutingkey"
  SPRING_RABBITMQ_HOST: "vault:eafdmmart/data/test/func/fdm#rabbitmqhost"
  SPRING_RABBITMQ_PORT: "vault:eafdmmart/data/test/func/fdm#rabbitmqport"
  SPRING_RABBITMQ_USERNAME: "vault:eafdmmart/data/test/func/fdm#rabbitmqusername"
  SPRING_RABBITMQ_PASSWORD: "vault:eafdmmart/data/test/func/fdm#rabbitmqpassword"
  SPRING_RABBITMQ_VIRTUAL_HOST: "vault:eafdmmart/data/test/func/fdm#rabbitmqvirtualhost"
  INTEGRATION_CAPABILITY_SERVER_URL: "vault:eafdmmart/data/test/func/fdm#capabilityserver"
  INTEGRATION_TECHRADAR_SERVER_URL: "vault:eafdmmart/data/test/func/fdm#techradarserverurl"
  INTEGRATION_AUTHSSO_SERVER_URL: "vault:eafdmmart/data/test/func/ambassador#authsso"
  OTEL_EXPORTER_OTLP_ENDPOINT: "vault:eafdmmart/data/test/func/fdm#opentelemetry"
  JWKS: "vault:eafdmmart/data/test/func/fdm#jwks"

podAnnotations:
  vault.security.banzaicloud.io/vault-addr: "https://vault-test.vimpelcom.ru/"

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: Content-Type, authorization
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, DELETE, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

resources:
  limits:
    cpu: 1000m
    memory: 3500Mi
  requests:
    cpu: 100m
    memory: 1256Mi
