env:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: "vault:eafdmmart/data/dev/fdm#url"
  SPRING_DATASOURCE_USERNAME: "vault:eafdmmart/data/dev/fdm#username"
  SPRING_DATASOURCE_PASSWORD: "vault:eafdmmart/data/dev/fdm#password"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "vault:eafdmmart/data/dev/fdm#driver"
  INTEGRATION_CAPABILITY_SERVER_URL: "vault:eafdmmart/data/dev/fdm#capabilityserver"
  INTEGRATION_TECHRADAR_SERVER_URL: "vault:eafdmmart/data/dev/fdm#techradarserverurl"
  JWKS: "vault:eafdmmart/data/dev/fdm#jwks"

podAnnotations:
  vault.security.banzaicloud.io/vault-addr: "https://vault-test.vimpelcom.ru/"

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: Content-Type, authorization
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, DELETE, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: 'true'

resources:
  limits:
    cpu: 1000m
    memory: 3500Mi
  requests:
    cpu: 100m
    memory: 1256Mi
