env:
  SPRING_PROFILES_ACTIVE: e2e
  SPRING_DATASOURCE_URL: "vault:eafdmmart/data/test/e2e/fdm#url"
  SPRING_DATASOURCE_USERNAME: "vault:eafdmmart/data/test/e2e/fdm#username"
  SPRING_DATASOURCE_PASSWORD: "vault:eafdmmart/data/test/e2e/fdm#password"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "vault:eafdmmart/data/test/e2e/fdm#driver"
  INTEGRATION_CAPABILITY_SERVER_URL: "vault:eafdmmart/data/test/e2e/fdm#capabilityserver"
  JWKS: "vault:eafdmmart/data/test/e2e/fdm#jwks"

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: Content-Type, authorization
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, DELETE, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: 'true'
